[package]
name = "cfdi"
version = "0.1.1"
edition = "2021"
description = "Crate for using Serde to import, deserialize and use CFDIs (Mexican Electronic Invoices) | Crate para importar CFDIs a Rust, usando Serde."
license = "MIT"


[dependencies]
